# Generated by Django 4.0.5 on 2022-06-29 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
